export default {
  OnBoarding: "OnBoarding",
  Login: "Login",
  Register: "Register",
  ForgotPassword: "Forgot Password",
  ChangePassword: "Change Password",
  ActivationCode: "Activation Page",
  Home: "Root",
  Discover: "Discovery",
  DiscoverHome: "Discover",
  NotFound: "NotFound",
  Give: "Give",
  Notification: "__$Notification",
  MediaPlayer: "__$Media Player",
  LiveVideo: "__$Live Video Player",
  MixlrMediaPlayer: "__$Mixlr Media Player",
  ContactUs: "__$Contact Us",
  PrayerRequest: "__$Prayer Request",
  CreatePrayerRequest: "__$Create Prayer Request",
  Testimony: "__$Testimony",
  CreateTestimony: "__$Create Testimony",
};
